apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: middleware:local
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_URL
          value: "http://app-service:8000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  selector:
    app: middleware
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP