apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "192.168.56.10"
  POSTGRES_PORT: "5432"